# Changes here will be overwritten by Copier
_commit: dd79d05
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: true
copyright_year: '2025'
documentation: true
email: mark@securehst.com
full_name: Mark Moreno
github_username: markm-io
has_cli: false
initial_commit: true
is_django_package: false
open_source_license: MIT
package_name: dataframe_schema_sync
project_name: Dataframe Schema Sync
project_short_description: This package will read a dataframe and will infer data
    types while storing the structure for later retrieval
project_slug: dataframe-schema-sync
run_uv_sync: true
setup_github: false
setup_pre_commit: true

